### ISSUE TITLE
Are you accepting contributions?

### ISSUE THREAD

**Issue by funkymonkeymonk** [stimm4711/GloomhavenCampaignTracker#17]
Hey,

I love the app and really appreciate you creating it. Are you willing to open source the code? That would allow others to contribute as well. I came here looking to see how this was built and to determine if I could figure out how to build a feature I was looking for, syncing multiple players' which you seem to have on the backlog already.

**Comment by stimm4711** [comment]
Hi,

I plan to move my sources from Azure DevOps to Github to make it OpenSource. But I don't know when. It will take some time.

**Comment by stimm4711** [comment]
Hi,

the code is now in this repository. If you still would like to work on the app you are welcome. 

Regards

**Comment by funkymonkeymonk** [comment]
Thanks. I'll take a look and see how I can be of value.
