### ISSUE TITLE
Add abilities for the classes

### ISSUE THREAD

**Issue by Fenix4k** [stimm4711/GloomhavenCampaignTracker#18]
Hey there

Thanks for this wonderful app, it is really helping to keep an overview.
What I miss the most is that abilities of the different classes have to be added manually and removed again when you change your deck
unless there's something I am missing, this would be a wonderful addition

**Comment by stimm4711** [comment]
Hi,

I don't know how you are using the app and why you are removing the abilities and change the deck. 
But the abilities are one thing I really would like to add to the app. It will be a lot of work to add all the cards and I don't want to spoil the unlocked classes for myself. So it will take some time until I will implement the abilities.

**Comment by Fenix4k** [comment]
i use it to track which abilities ive chosen on a character for the scenario...so i have to add and remove cards

but I understand you dont wanna spoil it for yourself! :)
 thanks for your work

**Comment by Entropy42** [comment]
I just commented on your BGG thread as well, but I'd be willing to create a text file of all the ability #s/names/levels.  Just give me the format you want it in, and you can just paste it all into your code without having to open and read your unlocked classes.

**Comment by stimm4711** [comment]
That would be great. I'll give you a JSON template with the fields I need.

**Comment by Entropy42** [comment]
Sounds good.  Do you only want cards lvl 2+?  I can't see why anyone would need to enter the base deck, since that is always unlocked.  One concern is that from reading on BGG, it appears some abilities have switched card numbers between the 1st and 2nd printing.  I'm going to use 2nd printing #s, since most people (including me) do not have a 1st printing copy.

**Comment by stimm4711** [comment]
The second printing is perfect. I need all cards because you can track the enhancements with my app. If I had all cards I would add the level one cards to the character from the start. And later I will add the images like I have for the items and events.

**Comment by stimm4711** [comment]
You can find the json here: [Classabilities.json](https://github.com/stimm4711/GloomhavenCampaignTracker/blob/master/Utils/Classabilities.json )

**Comment by Entropy42** [comment]
For the level, do you want that to be a string field or a number?  Because the starting cards have "1" or "X" for their level.

**Comment by stimm4711** [comment]
It should be numbers. All the starting cards should be level 1. There is no need (yet) to separate the x cards.

**Comment by Entropy42** [comment]
Here you go:
https://www.dropbox.com/s/unhafvhc9q4ofor/Classabilities.json?dl=0

**Comment by stimm4711** [comment]
Wow, that was fast. Thank you! 
I played the Saw class already. So it's no spoiler to me. You can write it here or send me mail to stimm@outlook.com.

**Comment by stimm4711** [comment]
Implemented the abilities.
