### ISSUE TITLE
Synchronizing campaing state between different devices.

### ISSUE THREAD

**Issue by rigmar** [stimm4711/GloomhavenCampaignTracker#19]
Hello!
Very convenient and useful application. Thank you very much! Is there at least one chance for the appearance of the function of synchronizing the current campaing state between different devices? Maybe in the form of support for Google Disc for backups?

**Comment by stimm4711** [comment]
Hi,
there is a chance. I want to add an option to share the data over wifi. One player starts a server and the others can connect to it as a client. The client can download a campaign and it will sync as long as the client is connected to the server. 
I suspended the work on it to do some other things I will release soon. Maybe I will continue working on it after that.
