### ISSUE TITLE
Automatically fill in treasure options for a scenario

### ISSUE THREAD

**Issue by Wires77** [stimm4711/GloomhavenCampaignTracker#40]
It would be nice if we didn't have to manually type in the treasure number and name for each scenario.  I understand you might not want to spoil yourself, but maybe you could take the treasure data from https://github.com/dmungin/gloomhaven-scenario-tree-ng/blob/master/src/assets/scenarios.json

**Comment by stimm4711** [comment]
That's true. I don't like the treasure managment too. When I find some time I will take care about it.

**Comment by Entropy42** [comment]
If I can be of assistance again on this one by cataloging the info, let me know.

**Comment by stimm4711** [comment]
It will be part of the new scenario management in 1.4.4
