### ISSUE TITLE
Automatically add achievements when completing a scenario

### ISSUE THREAD

**Issue by Wires77** [stimm4711/GloomhavenCampaignTracker#41]
Some unavailable scenarios stay unavailable when you've completed a scenario that doesn't directly unlock them, but unlocks an achievement that they require.  It'd be nice if I didn't have to leave the scenario page to add that achievement for the next scenario

**Comment by stimm4711** [comment]
My group is one scenario away from finishing the campaign. After that, when I find the time I will think about that.
