### ISSUE TITLE
Multilanguage support

### ISSUE THREAD

**Issue by mkrannich** [stimm4711/GloomhavenCampaignTracker#6]
Da die deutsche Version jetzt verfügbar ist, wäre es super, wenn die App auch deutsch kann.
Beteilige mich auch gerne bei der Einpflege der deutschen Texte.

**Comment by stimm4711** [comment]
Steht auf meiner todo Liste. Kann aber noch etwas dauern.

**Comment by stimm4711** [comment]
Wird nicht mehr umgesetzt. Die Karten zu übersetzen wäre zu großer Aufwand
